[env]
TERM = "xterm-256color"

# -------------------------
#          Fonts
# -------------------------
[font]
size = 12.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

# -------------------------
#         Keybinds
# -------------------------
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

# -------------------------
#       Other Settings
# -------------------------

[window.padding]
x = 10
y = 10

[window]
opacity = 0.70

[general]
import = [
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]
